#! /usr/bin/env bash

if [ $# -eq 0 ]; then
  echo "No bucket name boi!"
  exit 1
fi
BUCKET_NAME=$1
FILE_NAME=$2

OBJECT_KEY=$(basename "$FILE_NAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILE_NAME \
--key $OBJECT_KEY